name: Deploy to Server 👻

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: Deploy 📦
    runs-on: ubuntu-latest
    steps:
      - name: connect/deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: bash /bots/athena/deploy.sh
